<?php
$labels = array(
  'iusevimbtw.reply'     => 'Reply (r)',
  'iusevimbtw.replyall'     => 'Reply All (R)',
  'iusevimbtw.forward'     => 'Forward (f)',
  'iusevimbtw.delete'     => 'Delete (dd)',
  'iusevimbtw.archive'   => 'Archive (a)',
  'iusevimbtw.mark' => 'Mark (U)',
  'iusevimbtw.previous' => 'Previous (k)',
  'iusevimbtw.next' => 'Next (j)',
  'iusevimbtw.compose' => 'Compose (c)',
);
